name: Docker Test

on:
  push:
    branches:
      - main

jobs:
  docker-test:
    runs-on: [self-hosted, staging]

    steps:
      - uses: actions/checkout@v4

      - name: Stop Old Container
        run: |
          docker stop github-runner-test || true
          docker rm github-runner-test || true

      - name: Build Docker Image
        run: |
          docker build -t github-runner-image .

      - name: Run Docker Container
        run: |
          docker run -d \
            --name github-runner-test \
            -p 8080:80 \
            github-runner-image
