name: Docker Test

on:
  push:
    branches:
      - main

jobs:
  docker-test:
    runs-on: [self-hosted, staging]

    steps:
      - uses: actions/checkout@v4

      - name: Stop Old Container
        run: |
          docker stop github-runner-test || true
          docker rm github-runner-test || true

