name: Runner Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, staging]

    steps:
      - name: Test Runner
        run: |
          echo "RUNNER WORKING SUCCESSFULLY"
          hostname
          whoami
          pwd
